name: dalitzstudies
channels:
  - conda-forge
dependencies:
  - afterimage=1.21
  - anyio=3.7.1
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - asttokens=2.2.1
  - async-lru=2.0.4
  - atk-1.0=2.38.0
  - attrs=23.1.0
  - awkward=1.10.3
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - boost=1.82.0
  - boost-cpp=1.82.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-compiler=1.6.0
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - cctools=973.0.1
  - cctools_osx-arm64=973.0.1
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfitsio=4.2.0
  - charset-normalizer=3.2.0
  - clang=15.0.7
  - clang-15=15.0.7
  - clang_osx-arm64=15.0.7
  - clangxx=15.0.7
  - clangxx_osx-arm64=15.0.7
  - colorama=0.4.6
  - comm=0.1.4
  - compiler-rt=15.0.7
  - compiler-rt_osx-arm64=15.0.7
  - compilers=1.6.0
  - contourpy=1.1.0
  - cxx-compiler=1.6.0
  - cycler=0.11.0
  - davix=0.8.4
  - debugpy=1.6.8
  - decorator=5.1.1
  - defusedxml=0.7.1
  - eigen=3.4.0
  - entrypoints=0.4
  - exceptiongroup=1.1.2
  - executing=1.2.0
  - expat=2.5.0
  - fftw=3.3.10
  - flit-core=3.9.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.42.0
  - fortran-compiler=1.6.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - ftgl=2.4.0
  - gdk-pixbuf=2.42.10
  - gettext=0.21.1
  - gfortran=12.2.0
  - gfortran_impl_osx-arm64=12.2.0
  - gfortran_osx-arm64=12.2.0
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - gmp=6.2.1
  - graphite2=1.3.13
  - graphviz=8.1.0
  - gsl=2.7
  - gsoap=2.8.123
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=7.3.0
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.0
  - ipykernel=6.25.0
  - ipyparallel=8.6.1
  - ipython=8.14.0
  - isl=0.25
  - isoduration=20.11.0
  - jedi=0.19.0
  - jinja2=3.1.2
  - json5=0.9.14
  - jsonpointer=2.0
  - jsonschema=4.18.6
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.18.6
  - jupyter-lsp=2.2.0
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - jupyter_events=0.7.0
  - jupyter_server=2.7.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.24.0
  - kiwisolver=1.4.4
  - krb5=1.21.1
  - lcms2=2.15
  - ld64=609
  - ld64_osx-arm64=609
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang-cpp15=15.0.7
  - libcurl=8.2.1
  - libcxx=16.0.6
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran-devel_osx-arm64=12.2.0
  - libgfortran5=12.3.0
  - libglib=2.76.4
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnghttp2=1.52.0
  - libopenblas=0.3.23
  - libpng=1.6.39
  - librsvg=2.56.3
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libtool=2.4.7
  - libwebp=1.3.1
  - libwebp-base=1.3.1
  - libxcb=1.15
  - libxml2=2.11.4
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - llvm-tools=15.0.7
  - llvmlite=0.40.1
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - metakernel=0.29.5
  - mistune=3.0.0
  - mpc=1.3.1
  - mpfr=4.2.0
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert-core=7.7.3
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nlohmann_json=3.11.2
  - notebook=7.0.1
  - notebook-shim=0.2.3
  - numba=0.57.1
  - numpy=1.24.4
  - openjpeg=2.5.0
  - openssl=3.1.2
  - overrides=7.3.1
  - packaging=23.1
  - pandocfilters=1.5.0
  - pango=1.50.14
  - parso=0.8.3
  - pcre=8.45
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.0
  - pip=23.2.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - portalocker=2.7.0
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyobjc-core=9.2
  - pyobjc-framework-cocoa=9.2
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - pythia8=8.309
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python-json-logger=2.0.7
  - python-xxhash=3.2.0
  - python_abi=3.11
  - pytz=2023.3
  - pyyaml=6.0
  - pyzmq=25.1.0
  - readline=8.2
  - referencing=0.30.0
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - root=6.28.4
  - root_base=6.28.4
  - rpds-py=0.9.2
  - scitokens-cpp=1.0.2
  - scons=4.5.2
  - send2trash=1.8.2
  - setuptools=68.0.0
  - sigtool=0.1.3
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - stack_data=0.6.2
  - tapi=1100.0.11
  - tbb=2021.10.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - typing_utils=0.1.0
  - tzdata=2023c
  - uproot=4.3.7
  - uproot-base=4.3.7
  - uri-template=1.3.0
  - urllib3=2.0.4
  - vdt=0.4.3
  - vector-classes=1.4.3
  - wcwidth=0.2.6
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.1
  - wheel=0.41.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xrootd=5.6.1
  - xxhash=0.8.1
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - appdirs==1.4.4
      - configargparse==1.7
      - connection-pool==0.0.3
      - datrie==0.8.2
      - docutils==0.20.1
      - dpath==2.1.6
      - gitdb==4.0.10
      - gitpython==3.1.32
      - humanfriendly==10.0
      - plac==1.3.5
      - pulp==2.7.0
      - reretry==0.11.8
      - smart-open==6.3.0
      - smmap==5.0.0
      - snakemake==7.32.0
      - stopit==1.1.2
      - tabulate==0.9.0
      - throttler==1.2.2
      - toposort==1.10
      - wrapt==1.15.0
      - yte==1.5.1
